#!/bin/sh

CC=$(ls /usr/bin/gcc3* | tail -n1)
./configure --target-list=$(uname -i)-softmmu --cc=$CC --disable-kqemu \
        --extra-cflags="-I $PWD/../user" --extra-ldflags="-L $PWD/../user" \
	--enable-kvm --kernel-path=$PWD/../kernel
