#!/bin/sh

set -e

reload=1
install=
kvm=1

usage() {
    cat <<EOF 
usage: $0 [options]

options:
	--no-reload-module     do not reload kvm module
	--install              start up guest in installer boot cd
        --no-kvm               use standard qemu, without kvm
	--help                 this help
EOF
    exit 1
}

while [[ "$1" = -* ]]; do
    opt="$1"
    shift
    case "$opt" in
	--no-reload-module)
	    reload=
	    ;;
	--install)
	    install=1
	    ;;
	--no-kvm)
	    kvm=
	    ;;
	--help)
	    usage
	    ;;
	*)
	    usage
	    ;;
    esac
done

if [[ -n "$kvm" && -n "$reload" ]]; then
    if /sbin/lsmod | grep -q '^kvm '; then
	sudo /sbin/rmmod kvm
    fi
    sudo /sbin/insmod ../kernel/kvm.ko
    sudo chmod a+rw /dev/hvm
fi

disk="/tmp/disk"
if [[ -n "$install" ]]; then
    dd < /dev/zero bs=1k count=1 of="$disk"
    dd < /dev/zero bs=1k count=1 of="$disk" seek=$((10*1024*1024-1))
fi

boodisk=c
if [[ -n "$install" ]]; then
    bootdisk=d
fi

cdrom=/data/mirror/fedora/core/5/x86_64/os/images/boot.iso

${kvm:+./x86_64-softmmu/}qemu-system-x86_64 -cdrom "$cdrom" -boot "$bootdisk" -L /usr/share/qemu -hda "$disk" -m 384 -serial file:serial.log
