#ifndef __HVM_MMU_H
#define __HVM_MMU_H

#define PT64_ENT_PER_PAGE 512

#define PT64_WRITABLE_SHIFT 1

#define PT64_PRESENT_MASK (1ULL << 0)
#define PT64_WRITABLE_MASK (1ULL << PT64_WRITABLE_SHIFT)
#define PT64_USER_MASK (1ULL << 2)
#define PT64_PWT_MASK (1ULL << 3)
#define PT64_PCD_MASK (1ULL << 4)
#define PT64_ACCESSED_MASK (1ULL << 5)
#define PT64_DIRTY_MASK (1ULL << 6)
#define PT64_PAGE_SIZE_MASK (1ULL << 7)
#define PT64_PAT_MASK (1ULL << 7)
#define PT64_GLOBAL_MASK (1ULL << 8)
#define PT64_NX_MASK (1ULL << 63)

#define PT64_PAT_SHIFT 7
#define PT64_DIR_PAT_SHIFT 12
#define PT64_DIR_PAT_MASK (1ULL << PT64_DIR_PAT_SHIFT)

#define PT64_ROOT_LEVEL 4
#define PT64_DIRECTORY_LEVEL 2
#define PT64_PAGE_TABLE_LEVEL 1

#define PT64_BASE_ADDR_MASK (((1ULL << 52) - 1) & PAGE_MASK)
#define PT64_DIR_BASE_ADDR_MASK (PT64_BASE_ADDR_MASK & ~PT64_DIR_PAT_MASK)

#define PT64_PTE_COPY_MASK \
	(PT64_PRESENT_MASK | PT64_PWT_MASK | PT64_PCD_MASK | \
	PT64_ACCESSED_MASK | PT64_DIRTY_MASK | PT64_PAT_MASK | \
	PT64_GLOBAL_MASK | PT64_NX_MASK)

#define PT64_NON_PTE_COPY_MASK \
	(PT64_PRESENT_MASK | PT64_PWT_MASK | PT64_PCD_MASK | \
	PT64_ACCESSED_MASK | PT64_DIRTY_MASK | PT64_NX_MASK)

#define PT64_FIRST_AVAIL_BITS_SHIFT 9
#define PT64_SECOND_AVAIL_BITS_SHIFT 52

#define PT64_SHADOW_PS_MARK (1ULL << PT64_FIRST_AVAIL_BITS_SHIFT)
#define PT64_SHADOW_IO_MARK (1ULL << PT64_FIRST_AVAIL_BITS_SHIFT)

#define PT64_SHADOW_WRITABLE_SHIFT (PT64_FIRST_AVAIL_BITS_SHIFT + 1)
#define PT64_SHADOW_WRITABLE_MASK (1ULL << PT64_SHADOW_WRITABLE_SHIFT)

#define PT64_SHADOW_USER_SHIFT (PT64_SHADOW_WRITABLE_SHIFT + 1)
#define PT64_SHADOW_USER_MASK (1ULL << (PT64_SHADOW_USER_SHIFT))

#define PT64_SHADOW_BITS_OFFSET (PT64_SHADOW_WRITABLE_SHIFT - PT64_WRITABLE_SHIFT)

#define VALID_PAGE(x) ((x) != INVALID_PAGE)

#define PT64_LEVEL_BITS 9

#define PT64_LEVEL_SHIFT(level) \
		( PAGE_SHIFT + (level - 1) * PT64_LEVEL_BITS )

#define PT64_LEVEL_MASK(level) \
		(((1 << PT64_LEVEL_BITS) - 1) << PT64_LEVEL_SHIFT(level))

#define PT64_INDEX(address, level)\
	(((address) >> PT64_LEVEL_SHIFT(level)) & ((1 << PT64_LEVEL_BITS) - 1))


#define PFERR_PRESENT_MASK (1 << 0)
#define PFERR_WRITE_MASK (1 << 1)
#define PFERR_USER_MASK (1 << 2)


#endif
