EXTRA_CFLAGS := -I$(src)/include
obj-64-$(CONFIG_X86_64) := kvm-amd.o
obj-m := kvm.o kvm-intel.o $(obj-64-y)
kvm-objs := kvm_main.o mmu.o x86_emulate.o debug.o
kvm-intel-objs := vmx.o
kvm-amd-objs := svm.o
