obj-m := kvm.o kvm-intel.o

kvm-objs := kvm_main.o ioapic.o coalesced_mmio.o kvm-ia64.o kvm_fw.o \
	../anon_inodes.o ../external-module-compat.o

EXTRA_CFLAGS_vcpu.o += -mfixed-range=f2-f5,f12-f127
kvm-intel-objs := vmm.o vmm_ivt.o trampoline.o vcpu.o optvfault.o mmio.o \
               vtlb.o process.o memset.o memcpy.o
